"""Agent 8 — Deployer: packages working code, generates report, and creates downloadable artifact."""

from __future__ import annotations
import os
import textwrap
import zipfile
from datetime import datetime
from pathlib import Path

from loguru import logger

from core.config import settings
from core.models import Blueprint, DeploymentPackage, ProblemGraph
from llm.client import get_client
from llm.router import router


class DeployerAgent:
    """Packages and deploys a working agent, generates the final report."""

    async def deploy(
        self,
        code: str,
        execution_output: str,
        problem: ProblemGraph,
        blueprint: Blueprint,
        session_id: str = "DEMO",
    ) -> DeploymentPackage:
        """Create a complete deployment package for the working agent."""
        logger.info(f"Deploying {blueprint.agent_name}...")

        requirements = self._generate_requirements(blueprint)
        env_example = self._generate_env_example(blueprint)
        setup_script = self._generate_setup_script(blueprint)
        readme = self._generate_readme(blueprint, problem, execution_output)
        report = await self._generate_report(blueprint, problem, execution_output)

        # Write files to disk
        output_dir = settings.generated_dir / session_id
        output_dir.mkdir(parents=True, exist_ok=True)

        dockerfile = self._generate_dockerfile(blueprint)
        docker_compose = self._generate_docker_compose(blueprint)
        tests_code = self._generate_tests(blueprint, code)
        monitoring = self._generate_monitoring(blueprint)
        github_ci = self._generate_github_ci(blueprint)

        files = {
            "agent.py": code,
            "requirements.txt": requirements,
            ".env.example": env_example,
            "setup.sh": setup_script,
            "README.md": readme,
            "REPORT.md": report,
            "Dockerfile": dockerfile,
            "docker-compose.yml": docker_compose,
            "tests/test_agent.py": tests_code,
            "monitoring.py": monitoring,
            ".github/workflows/ci.yml": github_ci,
        }

        for filename, content in files.items():
            filepath = output_dir / filename
            filepath.parent.mkdir(parents=True, exist_ok=True)
            filepath.write_text(content, encoding="utf-8")

        zip_path = self._create_zip(output_dir, blueprint.agent_name, files)

        logger.success(f"Deployment package created: {zip_path}")

        return DeploymentPackage(
            agent_name=blueprint.agent_name,
            agent_code=code,
            requirements=requirements,
            readme=readme,
            setup_script=setup_script,
            env_example=env_example,
            report=report,
            output_dir=str(output_dir),
            zip_path=zip_path,
        )

    def _generate_requirements(self, blueprint: Blueprint) -> str:
        base = textwrap.dedent("""
            # Auto-generated by Spoke
            httpx==0.26.0
            loguru==0.7.2
            tenacity==8.2.3
            rich==13.7.1
            pydantic==2.6.3
            python-dotenv==1.0.1
            aiofiles==23.2.1
        """).strip()

        extras = []
        for tool in blueprint.tools_required:
            name_lower = tool.name.lower()
            if "gmail" in name_lower or "google" in name_lower:
                extras += ["google-api-python-client==2.120.0", "google-auth-httplib2==0.2.0", "google-auth-oauthlib==1.2.0"]
            elif "slack" in name_lower:
                extras.append("slack-sdk==3.27.0")
            elif "notion" in name_lower:
                extras.append("notion-client==2.2.1")
            elif "hubspot" in name_lower or "crm" in name_lower:
                extras.append("hubspot-api-client==8.2.1")
            elif "openai" in name_lower:
                extras.append("openai==1.13.3")
            elif "anthropic" in name_lower:
                extras.append("anthropic==0.21.3")

        seen = set()
        unique_extras = [x for x in extras if not (x in seen or seen.add(x))]
        if unique_extras:
            base += "\n\n# Integration-specific\n" + "\n".join(unique_extras)
        return base

    def _generate_env_example(self, blueprint: Blueprint) -> str:
        lines = ["# Environment variables for " + blueprint.agent_name, "# Copy to .env and fill in your values", ""]
        for tool in blueprint.tools_required:
            name_upper = tool.name.upper().replace(" ", "_").replace("-", "_")
            auth = tool.auth.lower()
            if "oauth" in auth:
                lines.append(f"GOOGLE_SERVICE_ACCOUNT_FILE=credentials.json  # {tool.name} OAuth2")
            elif "api key" in auth:
                lines.append(f"{name_upper}_API_KEY=your_{name_upper.lower()}_key_here")
            else:
                lines.append(f"{name_upper}_TOKEN=your_token_here")

        lines += [
            "",
            "# HuggingFace (for LLM extraction)",
            "HF_API_TOKEN=hf_your_token_here",
            "",
            "# Agent settings",
            "POLL_INTERVAL_SECONDS=60",
            "LOG_FILE=logs/agent.log",
        ]
        return "\n".join(lines)

    def _generate_setup_script(self, blueprint: Blueprint) -> str:
        return textwrap.dedent(f"""
            #!/bin/bash
            # Setup script for {blueprint.agent_name}
            # Generated by Spoke — "You spoke. It shipped."

            set -e

            echo "🤖 Setting up {blueprint.agent_name}..."

            # Create virtual environment
            python3 -m venv .venv
            source .venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt -q

            # Create directories
            mkdir -p logs

            # Copy env template
            if [ ! -f .env ]; then
                cp .env.example .env
                echo "⚠️  Created .env from template — please add your credentials"
            fi

            echo ""
            echo "✓ Setup complete!"
            echo ""
            echo "Next steps:"
            echo "  1. Edit .env with your API credentials"
            echo "  2. Run demo:       python agent.py --mode demo"
            echo "  3. Run for real:   python agent.py --mode production"
            echo ""
            echo "Built by Spoke | You spoke. It shipped."
        """).strip()

    def _generate_readme(self, blueprint: Blueprint, problem: ProblemGraph, execution_output: str) -> str:
        steps_md = "\n".join(f"{i+1}. {s}" for i, s in enumerate(blueprint.processing_steps))
        tools_md = "\n".join(f"- **{t.name}**: {t.purpose}" for t in blueprint.tools_required)
        hours_year = problem.estimated_hours_per_week * 52
        cost_year = hours_year * 35

        return textwrap.dedent(f"""
            # {blueprint.agent_name}
            > {blueprint.agent_description}

            *Built by [Spoke](https://spoke.ai) — "You spoke. It shipped."*

            ---

            ## Problem Solved
            {problem.core_pain}

            **Time saved:** {problem.estimated_hours_per_week:.0f} hrs/week → {hours_year:.0f} hrs/year → ~${cost_year:,.0f} saved annually

            ## How It Works
            {steps_md}

            ## Tools Used
            {tools_md}

            ## Quick Start

            ```bash
            ./setup.sh
            # Edit .env with your credentials
            python agent.py --mode demo        # zero-credential demo
            python agent.py --mode production  # live agent
            ```

            ## Demo Output
            ```
            {execution_output[:800]}
            ```

            ## Files
            | File | Purpose |
            |------|---------|
            | `agent.py` | The autonomous agent |
            | `requirements.txt` | Python dependencies |
            | `.env.example` | Environment variable template |
            | `setup.sh` | One-command setup script |

            ---
            *Built with Spoke — turn a 60-second video into a deployed agent.*
        """).strip()

    async def _generate_report(
        self, blueprint: Blueprint, problem: ProblemGraph, execution_output: str
    ) -> str:
        """Generate a human-readable impact report using LLM."""
        hours_year = problem.estimated_hours_per_week * 52
        cost_year = hours_year * 35

        template = textwrap.dedent(f"""
            # 🤖 {blueprint.agent_name} — Impact Report
            *Generated by Spoke on {datetime.now().strftime('%Y-%m-%d at %H:%M')}*

            ---

            ## What Was Built
            **{blueprint.agent_description}**

            This agent was designed and coded autonomously from a 60-second voice description.

            ## Problem Eliminated
            > "{problem.core_pain}"

            - **Frequency:** {problem.frequency}
            - **Time wasted:** {problem.estimated_hours_per_week:.0f} hours/week
            - **Root cause:** {', '.join(problem.process_steps[:3])}...

            ## Time Saved
            | Timeframe | Hours Saved | Value (@ $35/hr) |
            |-----------|-------------|-----------------|
            | Per week  | {problem.estimated_hours_per_week:.0f} hrs | ${problem.estimated_hours_per_week * 35:,.0f} |
            | Per month | {problem.estimated_hours_per_week * 4.3:.0f} hrs | ${problem.estimated_hours_per_week * 4.3 * 35:,.0f} |
            | Per year  | {hours_year:.0f} hrs | ${cost_year:,.0f} |

            ## Live Demo Output
            ```
            {execution_output[:600]}
            ```

            ## Architecture
            - **Type:** {blueprint.architecture_type}
            - **Trigger:** every {blueprint.trigger_mechanism.interval_seconds}s
            - **Tools integrated:** {', '.join(t.name for t in blueprint.tools_required)}

            ---
            *Built by Spoke — You spoke. It shipped.*
        """).strip()
        return template

    def _generate_dockerfile(self, blueprint: Blueprint) -> str:
        name_lower = blueprint.agent_name.lower().replace(" ", "_")
        return textwrap.dedent(f"""
            FROM python:3.11-slim

            LABEL org.opencontainers.image.title="{blueprint.agent_name}"
            LABEL org.opencontainers.image.description="{blueprint.agent_description}"
            LABEL org.opencontainers.image.source="Built by Spoke"

            WORKDIR /app

            RUN apt-get update && apt-get install -y --no-install-recommends \\
                gcc curl \\
                && rm -rf /var/lib/apt/lists/*

            COPY requirements.txt .
            RUN pip install --no-cache-dir -r requirements.txt

            COPY . .

            RUN mkdir -p logs storage

            ENV PYTHONUNBUFFERED=1
            ENV PYTHONPATH=/app

            HEALTHCHECK --interval=60s --timeout=10s --start-period=5s \\
                CMD python -c "import sqlite3; sqlite3.connect('storage/{name_lower}_cache.db')" || exit 1

            CMD ["python", "agent.py", "--mode", "production"]
        """).strip()

    def _generate_docker_compose(self, blueprint: Blueprint) -> str:
        name_lower = blueprint.agent_name.lower().replace(" ", "_")
        return textwrap.dedent(f"""
            version: "3.9"

            services:
              {name_lower}:
                build: .
                container_name: {name_lower}
                restart: unless-stopped
                env_file: .env
                volumes:
                  - ./logs:/app/logs
                  - ./storage:/app/storage
                  - ./credentials.json:/app/credentials.json:ro
                logging:
                  driver: json-file
                  options:
                    max-size: "10m"
                    max-file: "3"

              # Optional: Redis for distributed dedup in multi-instance deployments
              # redis:
              #   image: redis:7-alpine
              #   restart: unless-stopped
        """).strip()

    def _generate_tests(self, blueprint: Blueprint, code: str) -> str:
        name = blueprint.agent_name
        return textwrap.dedent(f"""
            \"\"\"Auto-generated tests for {name} — generated by Spoke.\"\"\"

            import asyncio
            import pytest
            import sys
            from pathlib import Path

            sys.path.insert(0, str(Path(__file__).parent.parent))


            def test_agent_module_imports():
                \"\"\"Agent module must import without errors.\"\"\"
                import importlib.util
                spec = importlib.util.spec_from_file_location("agent", Path(__file__).parent.parent / "agent.py")
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)
                assert hasattr(module, "demo")
                assert hasattr(module, "main")


            @pytest.mark.asyncio
            async def test_demo_runs_successfully():
                \"\"\"Demo mode must complete without raising exceptions.\"\"\"
                import subprocess, sys
                result = subprocess.run(
                    [sys.executable, "agent.py", "--mode", "demo"],
                    capture_output=True, text=True, timeout=60,
                    cwd=Path(__file__).parent.parent
                )
                assert result.returncode == 0, f"Demo failed:\\n{{result.stderr}}"


            def test_env_example_exists():
                assert (Path(__file__).parent.parent / ".env.example").exists()


            def test_requirements_complete():
                req = (Path(__file__).parent.parent / "requirements.txt").read_text()
                for pkg in ["loguru", "tenacity", "rich", "pydantic"]:
                    assert pkg in req, f"{{pkg}} missing from requirements.txt"
        """).strip()

    def _generate_monitoring(self, blueprint: Blueprint) -> str:
        name = blueprint.agent_name
        return textwrap.dedent(f"""
            \"\"\"
            {name} — Self-monitoring module.
            Run alongside the agent to track health and send alerts.
            Generated by Spoke.
            \"\"\"

            import os
            import sqlite3
            import time
            from datetime import datetime
            from pathlib import Path

            from loguru import logger

            CACHE_DB = os.getenv("CACHE_DB", "storage/{name.lower()}_cache.db")
            ALERT_EMAIL = os.getenv("ALERT_EMAIL", "")
            CHECK_INTERVAL = int(os.getenv("MONITOR_CHECK_INTERVAL", "300"))  # 5 min


            def get_stats() -> dict:
                \"\"\"Pull current stats from the dedup cache.\"\"\"
                try:
                    with sqlite3.connect(CACHE_DB) as conn:
                        total = conn.execute("SELECT COUNT(*) FROM processed_emails").fetchone()[0]
                        recent = conn.execute(
                            "SELECT COUNT(*) FROM processed_emails WHERE processed_at > datetime('now', '-1 hour')"
                        ).fetchone()[0]
                        return {{"total_processed": total, "last_hour": recent, "healthy": True}}
                except Exception as e:
                    return {{"error": str(e), "healthy": False}}


            def check_health() -> bool:
                \"\"\"Return True if agent is running and processing orders.\"\"\"
                stats = get_stats()
                if not stats.get("healthy"):
                    logger.error(f"Health check failed: {{stats.get('error')}}")
                    return False
                logger.info(f"Health: {{stats['total_processed']}} total, {{stats['last_hour']}} in last hour")
                return True


            if __name__ == "__main__":
                logger.info(f"{name} Monitor starting (check every {{CHECK_INTERVAL}}s)")
                while True:
                    check_health()
                    time.sleep(CHECK_INTERVAL)
        """).strip()

    def _generate_github_ci(self, blueprint: Blueprint) -> str:
        name = blueprint.agent_name
        return textwrap.dedent(f"""
            name: CI — {name}

            on:
              push:
                branches: [main]
              pull_request:
                branches: [main]

            jobs:
              test:
                runs-on: ubuntu-latest
                steps:
                  - uses: actions/checkout@v4

                  - name: Set up Python
                    uses: actions/setup-python@v5
                    with:
                      python-version: "3.11"
                      cache: pip

                  - name: Install dependencies
                    run: pip install -r requirements.txt pytest pytest-asyncio

                  - name: Run tests
                    run: pytest tests/ -v

                  - name: Run demo smoke test
                    run: python agent.py --mode demo

              docker:
                runs-on: ubuntu-latest
                needs: test
                if: github.ref == 'refs/heads/main'
                steps:
                  - uses: actions/checkout@v4
                  - name: Build Docker image
                    run: docker build -t {name.lower().replace(' ', '-')}:latest .
        """).strip()

    def _create_zip(self, output_dir: Path, agent_name: str, files: dict[str, str]) -> str:
        zip_name = f"{agent_name.lower().replace(' ', '_')}_spoke.zip"
        zip_path = str(output_dir / zip_name)
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for filename, content in files.items():
                zf.writestr(filename, content)
        return zip_path
